site_name: Cognitive Neuroscience Organization
site_description: Documentation for the Cognitive Neuroscience Organization's tools and resources
site_author: Cognitive Neuroscience Organization
site_url: https://github.com/Exios66/Cog_Neuroscience_Organization

repo_name: Exios66/Cog_Neuroscience_Organization
repo_url: https://github.com/Exios66/Cog_Neuroscience_Organization
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    primary: indigo
    accent: deep purple
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - search.suggest
    - search.highlight
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          selection:
            docstring_style: numpy
          rendering:
            show_source: true
  - git-revision-date-localized

nav:
  - Home: index.md
  - Getting Started: guides/getting_started.md
  - User Guide:
    - Installation: guides/installation.md
    - Basic Usage: guides/basic_usage.md
    - Advanced Usage: guides/advanced_usage.md
  - API Reference:
    - Imaging: api/imaging.md
    - Analysis: api/analysis.md
    - Visualization: api/visualization.md
    - Utils: api/utils.md
    - Models: api/models.md
  - Projects:
    - NeuroBridge: projects/neurobridge.md
    - Flexible Annotation Atlas: projects/flexible_annotation_atlas.md
    - Aesthetic Experience Framework: projects/aesthetic_experience_framework.md
  - Contributing: contributing.md
  - About: about.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Exios66/Cog_Neuroscience_Organization
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/example
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/example

copyright: Copyright &copy; 2023 Cognitive Neuroscience Organization 